Faq.create!([
  {question_text: "How can I contact the JML Domestic Violence Clinic?", answer_text: "Call us at 555-555-5555" },
   {question_text: "Where are you located?", answer_text: "315 S. Plymouth Court, Chicago, IL 60604"},
  {question_text: "question 3" , answer_text: "answer 3"},

])
Question.create!([
  {text: "Have you received a tax collection notice in the mail from the IRS? A tax\n\ncollection notice is a letter from the IRS that states your name, social security\n\nnumber, and the tax year at issue. The notice will also state the amount of tax due\n\nand any potential problems they found with your return.", yes_response: "Yes", no_response: "2", prequalifier: nil},
  {text: "Does this IRS notice relate to a joint tax return that you and your spouse filed\n\ntogether?", yes_response: "Yes", no_response: "3", prequalifier: nil},
  {text: "Did you first start receiving these tax notices from the IRS more than two years\n\nago?", yes_response: nil, no_response: "4", prequalifier: nil},
  {text: "Please look at the IRS notice and your tax return to see why this tax amount may\n\nbe due. Does the IRS claim that you owe money to them because of either of the\n\nfollowing:\n\na. Your spouse understated his income in the tax return? For example, your\n\nspouse earned money in that year and failed to report it on the tax return,\n\nor\n\nb. Your spouse included items of his to deduct from your income that did not\n\nexist or exaggerated these amounts? Common examples of deductions\n\ninclude interest paid on a mortgage, real estate taxes paid, or charitable\n\ndonations.\n\n1\n\nPlease be aware that if your tax return contained correct information, but you are not\n\ncurrently able to pay what is due under it, you should mark “No”, and will then be\n\ndirected to another set of questions that will help you determine if you qualify for\n\n“Equitable” based Innocent Spouse Relief.\n\nSimilarly, even if it was your income which was understated or your deductions which\n\nwere overstated, you should mark “No”, and will be directed to another set of questions\n\nthat will help you determine if you qualify for “Equitable” based innocent spouse relief\n\n(for example, if you were worried that your spouse would harm you or someone you\n\nloved if you asked him/her to read, explain, or change the return).", yes_response: nil, no_response: "5", prequalifier: nil},
  {text: "Is any of the following correct:\n\na. You did not sign the tax return? Or…\n\nb. You did not read the tax return prior to signing it because you worried\n\nyour spouse would harm you or someone you love if you asked him/her to\n\nread or explain it to you? Or…\n\nc. You did read and sign the return but did not see any potential problems\n\nwith the information based on your knowledge?\n\nPlease be aware that if you answer no to the above question because you did read\n\nthe return and you did see potential problems with the information, but were\n\nworried that your spouse would harm you or someone you loved if you asked\n\nhim/her to read or explain it to you, you still may be eligible for relief under\n\n“Equitable” based Innocent Spouse.", yes_response: nil, no_response: "6", prequalifier: nil},
  {text: "Would it be unfair for you to have to pay the tax rather than your spouse?\n\nThe IRS will consider it unfair for you to pay the tax if any of the following are\n\ntrue:\n\na. Your spouse was concealing income or was involved in\n\nwrongdoing which created the tax amount that is now due and you\n\ndid not knowingly or voluntarily do so. Or…\n\n2\n\nb. You did not receive any significant benefit from the income that\n\nyour spouse hid from you. The amount you receive from your\n\nspouse for your living expenses is not considered a significant\n\nbenefit. Examples of significant benefits include expensive jewelry\n\nand vacations, renovations to your home, and new automobile\n\npurchases. Or…\n\nc. Your spouse has abandoned you and your family. Or…\n\nd. Your spouse controlled all of the household finances and would\n\nnot let you have access to them. Or...\n\ne. Payment of the tax will cause financial hardship with paying basic\n\nliving expenses. Or...\n\nf. You or your loved ones were victims of “domestic violence” on\n\nbehalf of your spouse (Please see below for examples of domestic\n\nviolence).\n\nIn thinking about what is “domestic violence” under (f) above, please note that\n\nDomestic violence has many forms and some examples include if your spouse did\n\nany of the following:\n\n- Physically harm or threaten you, your children, or other members of\n\n- Sexually abuse you, your children, or other members of your family\n\n- Make you afraid to disagree with him/her\n\n- Frequently criticizes or insults you in a cruel fashion that impacts your\n\n- Withhold money for food, clothing, or other basic needs\n\n- Make most or all the decisions for you, including financial decisions\n\n- Restrict or control who you could see or talk to or where you could go\n\n- Isolate you or keep you from contacting your family members and/or\n\n- Cause you to fear for your safety in any other way\n\n- Stalk you, your children, or other members of your family\n\n- Become violent when your spouse abuses alcohol or drugs\n\n- Not allow you to have a bank account or have access to the household\n\n- Have all of your income pay for family expenses while they use their\n\n- Allow you only to have an allowance from household income\n\n- Forge your name on documents\n\nyour family\n\nfeelings of self-worth and confidence in your own worth and judgment\n\nfriends\n\nbank accounts, debit cards, credit cards\n\nincome however they please", yes_response: "Yes", no_response: "7", prequalifier: nil},
  {text: "Based on your answers to these questions, it appears that you qualify to apply for\n\n“classic” innocent spouse relief under Section 6015 of the Internal Revenue Code. The\n\nIRS decision on whether to grant you relief from tax liability under the &#39;Innocent Spouse\n\nRelief&#39; under the “classic” portion of the IRC is also based on how they view the equities\n\nof your situation and they will look at other facts too, such as if payment of these taxes\n\nwould impose financial hardship to you.\n\nSee Form 8857, Request for Innocent Spouse Relief.\n\nForm 8857: https://www.irs.gov/pub/irs-pdf/f8857.pdf\n\nForm 8857 Instructions: https://www.irs.gov/pub/irs-pdf/i8857.pdf\n\nCheck back in the near future for an Interactive Form 8857 THAT the John Marshall Law\n\nSchool’s Domestic Violence Clinical Advocacy Program is currently working on. This\n\ninteractive format will aid users in filling out the form. We will be creating tips on how to\n\nfill out IRS Form to show how you qualify to apply for Innocent Spouse Relief and how\n\nthe equities of your situation should lead the IRS to grant this relief to you\n\nAlso, if you are interested in obtaining help from the John Marshall Law School’s Family\n\nLaw &amp; Domestic Violence Clinic with any legal issues you may have relating to the\n\nabuse you have suffered from an intimate partner, these organizations will help connect\n\nyou with our services.\n\nBetween Friends: http://www.betweenfriendschicago.org/aboutus.html\n\nChicago Children’s Advocacy Center: http://www.chicagocac.org/who-we- are/contact-\n\nus/\n\nFamily Rescue: http://www.familyrescueinc.org/\n\n24-Hour Crisis Line: 800-360- 6619", yes_response: nil, no_response: "8", prequalifier: nil}
])